cmake_minimum_required(VERSION 3.20)
project(gnn_fusion_benchmark LANGUAGES CXX C)
set(MKL_INTERFACE lp64)
set(MKL_THREADING gnu_thread)
find_package(MKL CONFIG REQUIRED)
find_package(OpenMP REQUIRED)
set(ENABLE_CUDA OFF)
add_subdirectory(../../fusion sparse_fusion EXCLUDE_FROM_ALL)
add_executable(gnn_fusion_benchmark benchmark.cpp)
target_compile_features(gnn_fusion_benchmark PRIVATE cxx_std_17)
target_compile_definitions(gnn_fusion_benchmark PRIVATE MKL)
target_compile_options(gnn_fusion_benchmark PRIVATE -march=native)
target_include_directories(gnn_fusion_benchmark PRIVATE
    ../../fusion/gcn ../../fusion/include ../../fusion/aggregation/include)
target_link_libraries(gnn_fusion_benchmark PRIVATE
    fusion swbench::swbench MKL::MKL OpenMP::OpenMP_CXX)
